### PR TITLE
Add download

### PR DESCRIPTION
**Pull request by Xyarz**

### CODE REVIEW

**Comment by zsigmas** [comment]
depends on https://github.com/insightsengineering/bsafe/pull/5

It will not pass the tests until that PR is merged. Remotes in DESCRIPTION points to `main` branch that does not incorporate the changes required for this branch to pass yet.

I have tested it on `bsafe@dev` in `terst_on_dev` branch, all tests pass.

**Comment by AStemke** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by AStemke** [comment]
recheck

**Comment by Xyarz** [comment]
recheck

**Review by zsigmas — COMMENTED** [review]
All good

**Review by zsigmas — APPROVED** [review]

**Pull request merged**
